#spring:
#  application:
#    name: lab02-redis
#  redis:
#    redisson:
#      file: classpath:redisson.yml


spring:
  application:
    name: springboot-redisson
  redis:
    redisson:
      config: |
        singleServerConfig:
          password: 123456
          address: "redis://127.0.0.1:6379"
          database: 1
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.FstCodec> {}
        transportMode: "NIO"

server:
  port: 9888