spring:
  cloud:
    stream:
      # Spring Cloud Stream RocketMQ 配置项
      bindings:
        testMessage:
          destination: test # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          producer:
            errorChannelEnabled: true
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        producer:
          sync: true # 是否同步发送消息，默认为 false 异步。
        binder:
          name-server:  rocket-namesvc.infrast.svc.cluster.local:9876  # RocketMQ Namesrv 地址
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          spaceMessage:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              group: test-group # 生产者分组
              sync: true # 是否同步发送消息，默认为 false 异步。
          spaceScheduMessage:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              group: ${rocketmq.space.schedu.group} # 生产者分组
              sync: true # 是否同步发送消息，默认为 false 异步。
      default-binder: rocketmq