stages:
  - maven-build
  - docker-build
  - deploy

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  PROJECT_NAME: $CI_PROJECT_NAME
  LOG_PATH_MAPPING: /mnt/logs/$CI_PROJECT_NAME:/mnt/logs/$CI_PROJECT_NAME
  PORT_MAPPING: 8191:8080
  DEV_IMAGE: $CI_REGISTRY/$CI_REGISTRY_NAMESPACE_DEV/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  EXTDEV_IMAGE: $CI_REGISTRY/$CI_REGISTRY_NAMESPACE_DEV/ext-$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

cache:
  paths:
    - .m2/repository/
    - lab00-interface-service/target/

maven-build:
  stage: maven-build
  image: registry-vpc.cn-hangzhou.aliyuncs.com/ejiayou-other/maven:3.6.3-jdk-8-v1
  script:
    - mvn clean package -Dautoconfig.skip=true -Dmaven.test.skip=true -Dmaven.test.failure.ignore=true
  only:
    - web
  tags:
    - dev-001

docker-build:
  stage: docker-build
  image: docker:19.03.1
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ls -l
    - ls -l price-service-service/target
    - docker build -t $DEV_IMAGE -f Dockerfile .
    - docker push $DEV_IMAGE
  only:
    - web
  tags:
    - dev-001

deploy-dev:
  stage: deploy
  image: docker:19.03.1
  variables:
    JAVA_OPTS: '-Dspring.profiles.active=dev -Dserver.port=8080 -Xmx512m -Xms512m -Duser.timezone=Asia/Shanghai -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - if [ -n "`docker ps -a|grep -w $PROJECT_NAME |awk {'print $1'}`" ];
      then docker rm -f $PROJECT_NAME;
      fi
    - docker run --restart always -d --name $PROJECT_NAME -v $LOG_PATH_MAPPING -p $PORT_MAPPING --env JAVA_OPTS="$JAVA_OPTS" $DEV_IMAGE
  only:
    - web
  tags:
    - dev-001
  environment:
    name: dev
    url: dev.ejiayou.com/lab00-interface-service/monitor/health

deploy-extdev:
  stage: deploy
  image: docker:19.03.1
  variables:
    JAVA_OPTS: '-Dspring.profiles.active=dev -Dserver.port=8080 -Xmx512m -Xms512m -Duser.timezone=Asia/Shanghai -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - if [ -n "`docker ps -a|grep -w $PROJECT_NAME |awk {'print $1'}`" ];
      then docker rm -f $PROJECT_NAME;
      fi
    - docker run --restart always -d --name $PROJECT_NAME -v $LOG_PATH_MAPPING -p $PORT_MAPPING --env JAVA_OPTS="$JAVA_OPTS" $EXTDEV_IMAGE
  only:
    - web
  tags:
    - extdev
  when: manual
  environment:
    name: extdev
    url: extdev.ejiayou.com/lab00-interface-service/monitor/health
